In [51]:
import pandas as pd
import numpy as np

In [52]:
df= pd. read_csv('student3.csv')
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [53]:
df.shape

(16, 5)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    16 non-null     int64
 1   name    16 non-null     object
 2   class   15 non-null     object
 3   marks   14 non-null     float64
 4   age     14 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 772.0+ bytes

In [55]:
df['class']

0      TE
1      TE
2      BE
3      TE
4      TE
5      BE
6      BE
7      be
8      TE
9      TE
10     BE
11     TE
12     TE
13     be
14    NaN
15     TE
Name: class, dtype: object

In [56]:
df['marks']

KeyError: 'marks'

In [60]:
df.columns

Index(['roll', 'name', 'class', 'marks ', 'age'], dtype='object')

In [62]:
df['marks ']#space

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5       NaN
6     65.34
7     68.33
8     56.75
9     56.75
10    78.66
11      NaN
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks , dtype: float64

In [64]:
#to remove leading and trailing spaces in column names
df.columns=df.columns.str.strip()
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [66]:
df['name']=df['name'].str.title()

In [68]:
df['class']=df['class'].str.upper()

In [70]:
df

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
9      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [72]:
##FOR DUPLICATE VALUES entire duplicate row 
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
dtype: bool

In [74]:
#to get how many duplicate values TRUE =1 and false=0 , su, will represent no of duplicate values
df.duplicated().sum()

1

In [76]:
#3TO DROP DUPLIATE VALUES
df.drop_duplicates(inplace=True)

In [78]:
df.duplicated().sum()

0

In [80]:
##TO DEAL WITH NOTaNUMBER OR MISSING VALUE
df.count()

roll     15
name     15
class    14
marks    13
age      13
dtype: int64

In [82]:
df.isnull()

     roll   name  class  marks    age
0   False  False  False  False  False
1   False  False  False  False  False
2   False  False  False  False  False
3   False  False  False  False  False
4   False  False  False  False   True
5   False  False  False   True  False
6   False  False  False  False  False
7   False  False  False  False  False
8   False  False  False  False  False
10  False  False  False  False   True
11  False  False  False   True  False
12  False  False  False  False  False
13  False  False  False  False  False
14  False  False   True  False  False
15  False  False  False  False  False

In [84]:
##column vise missing values sum
df.isnull().sum()

roll     0
name     0
class    1
marks    2
age      2
dtype: int64

In [86]:
df.isnull().sum().sum()

5

In [88]:
#to handle MISSING VALUES

In [90]:
#1 DROPPING all missing values
df.dropna()

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
15    15  Shalini    TE  63.45  20.0

In [96]:
## fill missing values with our own knowledge
df.columns
df['marks'].fillna(60)

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5     60.00
6     65.34
7     68.33
8     56.75
10    78.66
11    60.00
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64

In [104]:
df['marks'].fillna(df['marks'].mean())##fill with avg values

0     56.770000
1     59.770000
2     76.880000
3     69.660000
4     63.280000
5     67.753077
6     65.340000
7     68.330000
8     56.750000
10    78.660000
11    67.753077
12    74.120000
13    88.450000
14    59.330000
15    63.450000
Name: marks, dtype: float64

In [106]:
df['age'].fillna(df['age'].median())

0     22.0
1     21.0
2     19.0
3     20.0
4     21.0
5     20.0
6     19.0
7     23.0
8     20.0
10    21.0
11    23.0
12    22.0
13    21.0
14    21.0
15    20.0
Name: age, dtype: float64

In [114]:
df['class'].fillna(df['class'].mode()[0])

0     TE
1     TE
2     BE
3     TE
4     TE
5     BE
6     BE
7     BE
8     TE
10    BE
11    TE
12    TE
13    BE
14    TE
15    TE
Name: class, dtype: object

In [118]:
##SPECIAL METHODS TO FILL AT ONCE 
##PADDING METHOD
df.fillna(method='pad')
#taking vlaues above it in the missing place

C:\Users\krish\AppData\Local\Temp\ipykernel_2860\3543490651.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28  20.0
5      6   Ayesha    BE  63.28  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66  20.0
11    11   Surbhi    TE  78.66  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin    BE  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [124]:
#forward fill
df.ffill() #fills missing values from above

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28  20.0
5      6   Ayesha    BE  63.28  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66  20.0
11    11   Surbhi    TE  78.66  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin    BE  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [128]:
df.bfill(inplace=True)
#fills missing values by values below it

In [126]:
#to implement in original df use inplace command

In [130]:
df

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28  20.0
5      6   Ayesha    BE  65.34  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    BE  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66  23.0
11    11   Surbhi    TE  74.12  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    BE  88.45  21.0
14    14   Sachin    TE  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [132]:
#to make a copy of df ,copy or exact same database , when we do df1=df, it creates a reference
df1=df.copy()

In [157]:
l1=[12,24,56,78,26]

In [165]:
l2=l1

In [138]:
l2

(12, 24, 56, 78, 26)

In [159]:
l1[0] = 100

In [161]:
l1

[100, 24, 56, 78, 26]

In [167]:
l2

[100, 24, 56, 78, 26]

In [169]:
l3=l1.copy()

In [171]:
l3

[100, 24, 56, 78, 26]

In [173]:
l3[4]=[10,40]

In [175]:
l3

[100, 24, 56, 78, [10, 40]]

In [177]:
l1

[100, 24, 56, 78, 26]

In [185]:
l1[4]=[25,10]

In [187]:
l3

[100, 24, 56, 78, [10, 40]]