In [219]:
import pandas as pd

SERIES

In [221]:
s=pd.Series([2,4,67,33.2,10])
s

0     2.0
1     4.0
2    67.0
3    33.2
4    10.0
dtype: float64

In [222]:
s.dtype

dtype('float64')

In [223]:
s.size

5

In [224]:
s[4]

10.0

In [225]:
s[2]=0

In [226]:
s[3]=33.7

In [227]:
s

0     2.0
1     4.0
2     0.0
3    33.7
4    10.0
dtype: float64

In [228]:
s1=pd.Series([12,36,25,87,14,25,36],index=range(100,107))

In [229]:
s1

100    12
101    36
102    25
103    87
104    14
105    25
106    36
dtype: int64

In [230]:
s1[101]

36

In [231]:
##DATAFRAMES

In [232]:
roll=pd.Series([1,2,3,4,5])
name=pd.Series(['Ajinkya','Krishna','Dnyanesh','Natasha','Shubham'])
marks=pd.Series([90,98,58,62,51])

In [233]:
df=pd.DataFrame({
    'roll':roll,
    'Name':name,
    'Marks':marks})
df

   roll      Name  Marks
0     1   Ajinkya     90
1     2   Krishna     98
2     3  Dnyanesh     58
3     4   Natasha     62
4     5   Shubham     51

df.size

In [235]:
df.columns

Index(['roll', 'Name', 'Marks'], dtype='object')

In [236]:
import os
os.getcwd()

'C:\\Users\\krish\\Downloads\\Documents'

In [237]:
#download and laod dataset into it   //https://mitu.co.in/dataset/
df=pd.read_csv('student1.csv')
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [238]:
df1=pd.read_csv('student5.csv')

In [239]:
df1

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20

In [240]:
df.columns

Index(['1', 'anil', 'TE', '56.77', '22'], dtype='object')

In [241]:
df1.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [242]:
headers=['a','b','c','d','e']

In [243]:
#giving our own header names to file
df=pd.read_csv('student1.csv',names=headers)
df

    a        b   c      d   e
0   1     anil  TE  56.77  22
1   2     amit  TE  59.77  21
2   3   aniket  BE  76.88  19
3   4  ajinkya  TE  69.66  20
4   5     asha  TE  63.28  20
5   6   ayesha  BE  49.55  20
6   7     amar  BE  65.34  19
7   8    amita  BE  68.33  23
8   9     amol  TE  56.75  20
9  10    anmol  BE  78.66  21

In [244]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [245]:
df2=pd.read_csv('student3.tsv',sep='\t')
df2

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [246]:
df2.shape

(10, 5)

In [247]:
df2.size

50

In [248]:
list(df2.columns)#list of columns

['roll', 'name', 'class', 'marks', 'age']

In [249]:
df2.T

,0,1,2,3,4,5,6,7,8,9
roll,1,2,3,4,5,6,7,8,9,10
name,anil,amit,aniket,ajinkya,asha,ayesha,amar,amita,amol,anmol
class,TE,TE,BE,TE,TE,BE,BE,BE,TE,BE
marks,56.77,59.77,76.88,69.66,63.28,49.55,65.34,68.33,56.75,78.66
age,22,21,19,20,20,20,19,23,20,21

In [250]:
df2.dtypes

roll       int64
name      object
class     object
marks    float64
age        int64
dtype: object

In [251]:
#method to convert df(3D) to array of all values of each row
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [252]:
#to view particularly top 5 values
df.head()

   a        b   c      d   e
0  1     anil  TE  56.77  22
1  2     amit  TE  59.77  21
2  3   aniket  BE  76.88  19
3  4  ajinkya  TE  69.66  20
4  5     asha  TE  63.28  20

In [253]:
df.head(3) #top 3 values

   a       b   c      d   e
0  1    anil  TE  56.77  22
1  2    amit  TE  59.77  21
2  3  aniket  BE  76.88  19

In [254]:
df.tail()# botoom half of the values

    a       b   c      d   e
5   6  ayesha  BE  49.55  20
6   7    amar  BE  65.34  19
7   8   amita  BE  68.33  23
8   9    amol  TE  56.75  20
9  10   anmol  BE  78.66  21

In [255]:
df.sum()

a                                                   55
b    anilamitaniketajinkyaashaayeshaamaramitaamolanmol
c                                 TETEBETETEBEBEBETEBE
d                                               644.99
e                                                  205
dtype: object

In [256]:
#info function
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [257]:
df.describe() #gives aggregation information/ FOR ONLY NUMERIC COLUMNS

              a          d          e
count  10.00000  10.000000  10.000000
mean    5.50000  64.499000  20.500000
std     3.02765   9.207179   1.269296
min     1.00000  49.550000  19.000000
25%     3.25000  57.520000  20.000000
50%     5.50000  64.310000  20.000000
75%     7.75000  69.327500  21.000000
max    10.00000  78.660000  23.000000

In [258]:
##DATA SLICING

In [259]:
#index slicing ilock

In [260]:
df2.iloc[0:3,0:3]# first 3 rows and columns respectively

   roll    name class
0     1    anil    TE
1     2    amit    TE
2     3  aniket    BE

In [261]:
#new df with a PART of earlier df
a=df2.iloc[0:3,0:3]
a

   roll    name class
0     1    anil    TE
1     2    amit    TE
2     3  aniket    BE

In [262]:
df2.iloc[6:,1:4]

    name class  marks
6   amar    BE  65.34
7  amita    BE  68.33
8   amol    TE  56.75
9  anmol    BE  78.66

In [263]:
#to select specific rows which are not in sequence but randomly
df2.iloc[[2,3,5,7], 1:4]  #basically we create a list of indices taht we need and pass it,because we cannot pas sit directly as a parameter

      name class  marks
2   aniket    BE  76.88
3  ajinkya    TE  69.66
5   ayesha    BE  49.55
7    amita    BE  68.33

In [264]:
df2.iloc[[3,4,7],[0,2,3]]

   roll class  marks
3     4    TE  69.66
4     5    TE  63.28
7     8    BE  68.33

In [265]:
df2.iloc[6,1]

'amar'

In [266]:
#all the rows in name column
df2.loc[:,'name'] # CAN PASS specific indices

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [267]:
df2.loc[:,['name','marks']]

      name  marks
0     anil  56.77
1     amit  59.77
2   aniket  76.88
3  ajinkya  69.66
4     asha  63.28
5   ayesha  49.55
6     amar  65.34
7    amita  68.33
8     amol  56.75
9    anmol  78.66

In [268]:
df2.drop(3)

   roll    name class  marks  age
0     1    anil    TE  56.77   22
1     2    amit    TE  59.77   21
2     3  aniket    BE  76.88   19
4     5    asha    TE  63.28   20
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [269]:
df.drop([2,4,6,7])# by default only on rows

    a        b   c      d   e
0   1     anil  TE  56.77  22
1   2     amit  TE  59.77  21
3   4  ajinkya  TE  69.66  20
5   6   ayesha  BE  49.55  20
8   9     amol  TE  56.75  20
9  10    anmol  BE  78.66  21

In [270]:
df2.drop(["name","marks"],axis=1)# drop a column method 1

   roll class  age
0     1    TE   22
1     2    TE   21
2     3    BE   19
3     4    TE   20
4     5    TE   20
5     6    BE   20
6     7    BE   19
7     8    BE   23
8     9    TE   20
9    10    BE   21

In [271]:
#method 2 using transpose
df2.T

,0,1,2,3,4,5,6,7,8,9
roll,1,2,3,4,5,6,7,8,9,10
name,anil,amit,aniket,ajinkya,asha,ayesha,amar,amita,amol,anmol
class,TE,TE,BE,TE,TE,BE,BE,BE,TE,BE
marks,56.77,59.77,76.88,69.66,63.28,49.55,65.34,68.33,56.75,78.66
age,22,21,19,20,20,20,19,23,20,21

In [272]:
#RENAME

In [273]:
col={'roll':'id','marks':'grade'}#changes index
df2.rename(columns=col)

   id     name class  grade  age
0   1     anil    TE  56.77   22
1   2     amit    TE  59.77   21
2   3   aniket    BE  76.88   19
3   4  ajinkya    TE  69.66   20
4   5     asha    TE  63.28   20
5   6   ayesha    BE  49.55   20
6   7     amar    BE  65.34   19
7   8    amita    BE  68.33   23
8   9     amol    TE  56.75   20
9  10    anmol    BE  78.66   21

In [274]:
ind={1:'one',3:'three'} #changes not implemented in original dataframe
df2.rename(index=ind) #index no.chang

       roll     name class  marks  age
0         1     anil    TE  56.77   22
one       2     amit    TE  59.77   21
2         3   aniket    BE  76.88   19
three     4  ajinkya    TE  69.66   20
4         5     asha    TE  63.28   20
5         6   ayesha    BE  49.55   20
6         7     amar    BE  65.34   19
7         8    amita    BE  68.33   23
8         9     amol    TE  56.75   20
9        10    anmol    BE  78.66   21

###Iteration

In [276]:
for x in df2:
    print(x) #gives names of all columns

roll
name
class
marks
age

In [277]:
# to print all values in our df using a loop from a column
for x in df2:
    print(df2[x])

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: roll, dtype: int64
0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object
0    TE
1    TE
2    BE
3    TE
4    TE
5    BE
6    BE
7    BE
8    TE
9    BE
Name: class, dtype: object
0    56.77
1    59.77
2    76.88
3    69.66
4    63.28
5    49.55
6    65.34
7    68.33
8    56.75
9    78.66
Name: marks, dtype: float64
0    22
1    21
2    19
3    20
4    20
5    20
6    19
7    23
8    20
9    21
Name: age, dtype: int64

In [278]:
l = [13,45,67,23,13,10]
#index with value
for x in l:
    print(l.index(x),'->',x) #same index repeat

0 -> 13
1 -> 45
2 -> 67
3 -> 23
0 -> 13
5 -> 10

In [279]:
#enumerate 
l = [13,45,67,23,13,10]
for ind,ele in enumerate(l,start=10):
#start with 10th index
    
    print(ind,'->',ele)

10 -> 13
11 -> 45
12 -> 67
13 -> 23
14 -> 13
15 -> 10

In [280]:
#tuple of index and its values 
l = [13,45,67,23,13,10]
list(enumerate(l))

[(0, 13), (1, 45), (2, 67), (3, 23), (4, 13), (5, 10)]

In [281]:
df2=pd.read_csv('student3.tsv',sep='\t')
df2

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [282]:
df2.sort_values(by = 'class')

   roll     name class  marks  age
2     3   aniket    BE  76.88   19
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
9    10    anmol    BE  78.66   21
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
8     9     amol    TE  56.75   20

In [283]:
df2.sort_values(by=['class','marks'])

   roll     name class  marks  age
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
2     3   aniket    BE  76.88   19
9    10    anmol    BE  78.66   21
8     9     amol    TE  56.75   20
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
4     5     asha    TE  63.28   20
3     4  ajinkya    TE  69.66   20

In [284]:
#for descending
df2.sort_values(by='class',ascending=False)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
8     9     amol    TE  56.75   20
2     3   aniket    BE  76.88   19
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
9    10    anmol    BE  78.66   21

In [285]:
#methods on series

In [286]:
df2['marks'].min()

49.55

In [287]:
df2['marks'].max()

78.66

In [288]:
df2['marks'].median()

64.31

In [289]:
df2['marks'].mean()

64.499

In [290]:
df2['name'].str.upper() #every name converted to uppercase

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5     AYESHA
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [291]:
df2['name'].str.title() #to make first letter capital of all rows in column

0       Anil
1       Amit
2     Aniket
3    Ajinkya
4       Asha
5     Ayesha
6       Amar
7      Amita
8       Amol
9      Anmol
Name: name, dtype: object

In [292]:
df2['name'].str.len() #tells no of characters in each row in the column

0    4
1    4
2    6
3    7
4    4
5    6
6    4
7    5
8    4
9    5
Name: name, dtype: int64

In [293]:
df2['name'].str.startswith('A')

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: name, dtype: bool

In [294]:
df2['name'].str.startswith('a')

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: name, dtype: bool

In [295]:
df2['name'].str.endswith('A')

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: name, dtype: bool

In [296]:
df2['name'].str.endswith('a')

0    False
1    False
2    False
3     True
4     True
5     True
6    False
7     True
8    False
9    False
Name: name, dtype: bool

In [297]:
df2['name'].str.contains('n')

0     True
1    False
2     True
3     True
4    False
5    False
6    False
7    False
8    False
9     True
Name: name, dtype: bool

In [298]:
#how to add or modify columns

In [299]:
df2['roll']=df2['roll'] +100

df2

In [301]:
df2

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106   ayesha    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [302]:
gender=['M','M','M','M','M','F','M','F','M','F']

In [303]:
df2['gender']=gender
df2

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      M
1   102     amit    TE  59.77   21      M
2   103   aniket    BE  76.88   19      M
3   104  ajinkya    TE  69.66   20      M
4   105     asha    TE  63.28   20      M
5   106   ayesha    BE  49.55   20      F
6   107     amar    BE  65.34   19      M
7   108    amita    BE  68.33   23      F
8   109     amol    TE  56.75   20      M
9   110    anmol    BE  78.66   21      F

In [304]:
#CREATE A CGPA COLUMN
df2['cgpa']=(df2['marks'] /10)+1.5 
df2

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      M  7.177
1   102     amit    TE  59.77   21      M  7.477
2   103   aniket    BE  76.88   19      M  9.188
3   104  ajinkya    TE  69.66   20      M  8.466
4   105     asha    TE  63.28   20      M  7.828
5   106   ayesha    BE  49.55   20      F  6.455
6   107     amar    BE  65.34   19      M  8.034
7   108    amita    BE  68.33   23      F  8.333
8   109     amol    TE  56.75   20      M  7.175
9   110    anmol    BE  78.66   21      F  9.366

In [305]:
#to apply value counts on categories
df2['gender'].value_counts()

gender
M    7
F    3
Name: count, dtype: int64

In [306]:
df2['class'].value_counts()

class
TE    5
BE    5
Name: count, dtype: int64

In [307]:
df2['class'].mode()

0    BE
1    TE
Name: class, dtype: object

In [308]:
df2['class'].mode()[0]# required in data cleaning to get modes,decided on mode function above 0 or 1

'BE'

In [309]:
##GROUP BY= can use aggregation functions on data on other colunbs with categories

In [310]:
g= df2.groupby('class')

In [311]:
g.get_group('TE')

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      M  7.177
1   102     amit    TE  59.77   21      M  7.477
3   104  ajinkya    TE  69.66   20      M  8.466
4   105     asha    TE  63.28   20      M  7.828
8   109     amol    TE  56.75   20      M  7.175

In [312]:
g.groups

{'BE': [2, 5, 6, 7, 9], 'TE': [0, 1, 3, 4, 8]}

In [313]:
g['marks'].max()

class
BE    78.66
TE    69.66
Name: marks, dtype: float64

In [314]:
#aggregation function
import numpy as np
g['marks'].agg([min,max,np.mean,sum,np.median])

         min    max    mean     sum  median
class
BE     49.55  78.66  67.752  338.76   68.33
TE     56.75  69.66  61.246  306.23   59.77

In [315]:
#to remove warnings
import warnings 
warnings.filterwarnings('ignore')

In [316]:
#method 2
g['marks'].agg([min,max,np.mean,sum,np.median])

         min    max    mean     sum  median
class
BE     49.55  78.66  67.752  338.76   68.33
TE     56.75  69.66  61.246  306.23   59.77

In [317]:
g= df2.groupby('class')

In [431]:

df2.drop(['gender','cgpa'],axis=1)

KeyError: "['gender', 'cgpa'] not found in axis"

In [433]:
import pandas as pd
#to make changes in original df , use inplace command
#use inplace = True
df2

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106   ayesha    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [429]:
##create a dataframe df1 = gender,cgpa,roll
#roll no column same as df2
df1['roll']=df2['roll']
df1

   roll     name class  marks  age
0   101   surbhi    TE  67.44   23
1   102    sujay    TE  74.12   22
2   103  subhash    BE  82.44   21
3   104   sachin    TE  59.33   21
4   105  shalini    TE  63.45   20

In [437]:
df2['cgpa']=(df2['marks'] /10)+1.5 
df2['gender']=gender
df2

   roll     name class  marks  age   cgpa gender
0   101     anil    TE  56.77   22  7.177      M
1   102     amit    TE  59.77   21  7.477      M
2   103   aniket    BE  76.88   19  9.188      M
3   104  ajinkya    TE  69.66   20  8.466      M
4   105     asha    TE  63.28   20  7.828      M
5   106   ayesha    BE  49.55   20  6.455      F
6   107     amar    BE  65.34   19  8.034      M
7   108    amita    BE  68.33   23  8.333      F
8   109     amol    TE  56.75   20  7.175      M
9   110    anmol    BE  78.66   21  9.366      F

In [455]:
value=['roll','gender','cgpa']
df3=df2[value]
df3

   roll gender   cgpa
0   101      M  7.177
1   102      M  7.477
2   103      M  9.188
3   104      M  8.466
4   105      M  7.828
5   106      F  6.455
6   107      M  8.034
7   108      F  8.333
8   109      M  7.175
9   110      F  9.366

## sirs method

In [466]:
cgpa =(df2['marks']/10)+1.5
newdf=pd.DataFrame({
    'roll':range(101,111),
    'gender': gender,
    'cgpa':cgpa})

In [468]:
newdf

   roll gender   cgpa
0   101      M  7.177
1   102      M  7.477
2   103      M  9.188
3   104      M  8.466
4   105      M  7.828
5   106      F  6.455
6   107      M  8.034
7   108      F  8.333
8   109      M  7.175
9   110      F  9.366

In [474]:
##MERGE

In [476]:
pd.merge(df2,newdf,on='roll')

   roll     name class  marks  age  cgpa_x gender_x gender_y  cgpa_y
0   101     anil    TE  56.77   22   7.177        M        M   7.177
1   102     amit    TE  59.77   21   7.477        M        M   7.477
2   103   aniket    BE  76.88   19   9.188        M        M   9.188
3   104  ajinkya    TE  69.66   20   8.466        M        M   8.466
4   105     asha    TE  63.28   20   7.828        M        M   7.828
5   106   ayesha    BE  49.55   20   6.455        F        F   6.455
6   107     amar    BE  65.34   19   8.034        M        M   8.034
7   108    amita    BE  68.33   23   8.333        F        F   8.333
8   109     amol    TE  56.75   20   7.175        M        M   7.175
9   110    anmol    BE  78.66   21   9.366        F        F   9.366

In [478]:
newdf=pd.read_csv('student5.csv')

In [480]:
newdf

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20

In [484]:
##CONCATING
pd.concat([df2,newdf])

   roll     name class  marks  age   cgpa gender
0   101     anil    TE  56.77   22  7.177      M
1   102     amit    TE  59.77   21  7.477      M
2   103   aniket    BE  76.88   19  9.188      M
3   104  ajinkya    TE  69.66   20  8.466      M
4   105     asha    TE  63.28   20  7.828      M
5   106   ayesha    BE  49.55   20  6.455      F
6   107     amar    BE  65.34   19  8.034      M
7   108    amita    BE  68.33   23  8.333      F
8   109     amol    TE  56.75   20  7.175      M
9   110    anmol    BE  78.66   21  9.366      F
0     1   surbhi    TE  67.44   23    NaN    NaN
1     2    sujay    TE  74.12   22    NaN    NaN
2     3  subhash    BE  82.44   21    NaN    NaN
3     4   sachin    TE  59.33   21    NaN    NaN
4     5  shalini    TE  63.45   20    NaN    NaN

In [486]:
#for adding index later
pd.concat([df2,newdf],ignore_index=True)

    roll     name class  marks  age   cgpa gender
0    101     anil    TE  56.77   22  7.177      M
1    102     amit    TE  59.77   21  7.477      M
2    103   aniket    BE  76.88   19  9.188      M
3    104  ajinkya    TE  69.66   20  8.466      M
4    105     asha    TE  63.28   20  7.828      M
5    106   ayesha    BE  49.55   20  6.455      F
6    107     amar    BE  65.34   19  8.034      M
7    108    amita    BE  68.33   23  8.333      F
8    109     amol    TE  56.75   20  7.175      M
9    110    anmol    BE  78.66   21  9.366      F
10     1   surbhi    TE  67.44   23    NaN    NaN
11     2    sujay    TE  74.12   22    NaN    NaN
12     3  subhash    BE  82.44   21    NaN    NaN
13     4   sachin    TE  59.33   21    NaN    NaN
14     5  shalini    TE  63.45   20    NaN    NaN

In [488]:
mar=df2['marks']>60

In [490]:
df2[mar]

   roll     name class  marks  age   cgpa gender
2   103   aniket    BE  76.88   19  9.188      M
3   104  ajinkya    TE  69.66   20  8.466      M
4   105     asha    TE  63.28   20  7.828      M
6   107     amar    BE  65.34   19  8.034      M
7   108    amita    BE  68.33   23  8.333      F
9   110    anmol    BE  78.66   21  9.366      F

In [492]:
#method 2 
df2[df2['marks']>60]

   roll     name class  marks  age   cgpa gender
2   103   aniket    BE  76.88   19  9.188      M
3   104  ajinkya    TE  69.66   20  8.466      M
4   105     asha    TE  63.28   20  7.828      M
6   107     amar    BE  65.34   19  8.034      M
7   108    amita    BE  68.33   23  8.333      F
9   110    anmol    BE  78.66   21  9.366      F

In [504]:
#belonging to BE maerks >60
df2[(df2['marks']>60)&(df2['class']=='BE')]

   roll    name class  marks  age   cgpa gender
2   103  aniket    BE  76.88   19  9.188      M
6   107    amar    BE  65.34   19  8.034      M
7   108   amita    BE  68.33   23  8.333      F
9   110   anmol    BE  78.66   21  9.366      F

In [523]:
# data of names starting with 'an'
df2[(df2['marks']>60)& (df2['name'].str.startswith('an'))]

   roll    name class  marks  age   cgpa gender
2   103  aniket    BE  76.88   19  9.188      M
9   110   anmol    BE  78.66   21  9.366      F

In [528]:
##exporting to local machine
x=df2[(df2['marks']>60)&(df2['class']=='BE')]
x

   roll    name class  marks  age   cgpa gender
2   103  aniket    BE  76.88   19  9.188      M
6   107    amar    BE  65.34   19  8.034      M
7   108   amita    BE  68.33   23  8.333      F
9   110   anmol    BE  78.66   21  9.366      F

In [530]:
x.to_csv('op.csv',index=False)#to remove indices that come along with it 2,6,7,9