In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('mtcars.csv')

In [5]:
df.head()

    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [172]:
df.shape

(32, 11)

In [237]:

## seprate data
x=df[['cyl','hp','wt','disp']]
y=df['mpg']

In [239]:
#Normalisation
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [241]:
x_scaled=scaler.fit_transform(x)

In [243]:
# cross vaidation
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,random_state=0)

In [245]:
#linear regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x,y)

LinearRegression()

In [247]:
from sklearn.metrics import r2_score
lr.score(x,y)

0.8486347934212335

## recursive feature eliminatoin

In [223]:
from sklearn.feature_selection import RFE

In [282]:
x=df.drop('mpg',axis=1)

In [284]:

rfe=RFE(lr) ## passing lr model to rfe

In [286]:
rfe.fit(x,y)

RFE(estimator=LinearRegression())

In [288]:
print('training acc:',rfe.score(x,y))

training acc: 0.860794511117408

In [290]:
## to see what features it is considering true

In [292]:
rfe.get_support()

array([False, False, False,  True,  True,  True, False,  True, False,
        True])

In [294]:
x= x.iloc[:,rfe.get_support()]

In [296]:
x

    drat     wt   qsec  am  carb
0   3.90  2.620  16.46   1     4
1   3.90  2.875  17.02   1     4
2   3.85  2.320  18.61   1     1
3   3.08  3.215  19.44   0     1
4   3.15  3.440  17.02   0     2
5   2.76  3.460  20.22   0     1
6   3.21  3.570  15.84   0     4
7   3.69  3.190  20.00   0     2
8   3.92  3.150  22.90   0     2
9   3.92  3.440  18.30   0     4
10  3.92  3.440  18.90   0     4
11  3.07  4.070  17.40   0     3
12  3.07  3.730  17.60   0     3
13  3.07  3.780  18.00   0     3
14  2.93  5.250  17.98   0     4
15  3.00  5.424  17.82   0     4
16  3.23  5.345  17.42   0     4
17  4.08  2.200  19.47   1     1
18  4.93  1.615  18.52   1     2
19  4.22  1.835  19.90   1     1
20  3.70  2.465  20.01   0     1
21  2.76  3.520  16.87   0     2
22  3.15  3.435  17.30   0     2
23  3.73  3.840  15.41   0     4
24  3.08  3.845  17.05   0     2
25  4.08  1.935  18.90   1     1
26  4.43  2.140  16.70   1     2
27  3.77  1.513  16.90   1     2
28  4.22  3.170  14.50   1     4
29  3.62  2.770  15.50   1     6
30  3.54  3.570  14.60   1     8
31  4.11  2.780  18.60   1     2

# backward/forward

In [299]:
from sklearn.feature_selection import SequentialFeatureSelector

In [301]:
sfs=SequentialFeatureSelector(lr,direction='forward')

In [303]:
x=df.drop('mpg',axis=1)

In [305]:
sfs.fit(x,y)

SequentialFeatureSelector(estimator=LinearRegression())

In [307]:
sfs.get_support()

array([ True,  True,  True, False,  True, False,  True, False, False,
       False])

In [319]:
x= x.iloc[:,sfs.get_support()]

In [321]:
x

    cyl   disp   hp     wt  vs
0     6  160.0  110  2.620   0
1     6  160.0  110  2.875   0
2     4  108.0   93  2.320   1
3     6  258.0  110  3.215   1
4     8  360.0  175  3.440   0
5     6  225.0  105  3.460   1
6     8  360.0  245  3.570   0
7     4  146.7   62  3.190   1
8     4  140.8   95  3.150   1
9     6  167.6  123  3.440   1
10    6  167.6  123  3.440   1
11    8  275.8  180  4.070   0
12    8  275.8  180  3.730   0
13    8  275.8  180  3.780   0
14    8  472.0  205  5.250   0
15    8  460.0  215  5.424   0
16    8  440.0  230  5.345   0
17    4   78.7   66  2.200   1
18    4   75.7   52  1.615   1
19    4   71.1   65  1.835   1
20    4  120.1   97  2.465   1
21    8  318.0  150  3.520   0
22    8  304.0  150  3.435   0
23    8  350.0  245  3.840   0
24    8  400.0  175  3.845   0
25    4   79.0   66  1.935   1
26    4  120.3   91  2.140   0
27    4   95.1  113  1.513   1
28    8  351.0  264  3.170   0
29    6  145.0  175  2.770   0
30    8  301.0  335  3.570   0
31    4  121.0  109  2.780   1

In [323]:
lr=LinearRegression()
lr.fit(x,y)
lr.score(x,y)

0.8487727850467539